version: '2'
services:
  streetcat-app:
    image: streetcat
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      #      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/streetcat
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
#  streetcat-postgresql:
#    extends:
#      file: postgresql.yml
#      service: streetcat-postgresql
